title: PaulChing
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.9659498
  brandStrength: 0.5
  rhythmicContrast: 0.811828
  brandColors:
    - '#91A3BD'
    - '#4C5B77'
    - '#BDCFE0'
  lightness: 0.8476703
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: PaulChing
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.2204301
layout_spectrum: 1
